@extends('layouts.app')
@section('title','ソーシャル')
@section('body')
    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>ユーザID</th>
            <th>フォロー数</th>
            <th>フォロワー数</th>
            <th>所在地</th>
            <th>最終ログイン</th>
        </tr>
        </thead>
        @foreach($items as $item)
            <tr>
                <td>{{$item['id']}}</td>
                <td>{{$item['user_name']}}</td>
                <td>{{$item['follow']}}</td>
                <td>{{$item['follower']}}</td>
                <td>{{$item['locate']}}</td>
                <td>{{$item['last_login']}}</td>
            </tr>
        @endforeach
    </table>
@endsection
