###ユーザ情報取得
GET http://localhost:8000/api/users/1
Accept: application/json

###ユーザ一覧取得
GET http://localhost:8000/api/users
Accept: application/json

###メール一覧取得
GET http://localhost:8000/api/mails
Accept: application/json

###ステージ一覧取得
GET http://localhost:8000/api/stages
Accept: application/json

###アイテム一覧取得
GET http://localhost:8000/api/items
Accept: application/json

###ドロップステージ一覧取得
GET http://localhost:8000/api/drops
Accept: application/json

###使用可能ステージ一覧取得
GET http://localhost:8000/api/usables
Accept: application/json

###使用可能カード一覧取得
GET http://localhost:8000/api/battleMode/usableCard
Accept: application/json

###実績一覧取得
GET http://localhost:8000/api/Achievements
Accept: application/json

###バトルモード検索結果取得
GET http://localhost:8000/api/battleMode
Accept: application/json

###バトルモード検索結果取得
GET http://localhost:8000/api/battleMode/result/1
Accept: application/json

###所持アイテム検索結果取得
GET http://localhost:8000/api/userItems/1
Accept: application/json

###受信メール検索結果取得
GET http://localhost:8000/api/userMails/2
Accept: application/json

###所持実績検索結果取得
GET http://localhost:8000/api/userAchievements/1
Accept: application/json

###フォロー検索結果取得
GET http://localhost:8000/api/follows/1
Accept: application/json

###使用済みカード検索結果取得
GET http://localhost:8000/api/battleMode/usedCard/1
Accept: application/json

###防衛デッキ検索結果取得
GET http://localhost:8000/api/battleMode/defenseDeck/2
Accept: application/json

###ユーザ登録
POST http://localhost:8000/api/users/store
Content-Type: application/json
Accept: application/json

{
    "name": "mogu"
}

###ユーザ更新
POST http://localhost:8000/api/users/update
Content-Type: application/json
Accept: application/json

{
    "user_id": "101"
}

###所持アイテム更新
POST http://localhost:8000/api/userItems/update
Content-Type: application/json
Accept: application/json

{
    "user_id": "1",
    "item_id": "2",
    "use_item": "2",
    "get_item": "4"
}

###フォロー登録
POST http://localhost:8000/api/follows/store
Content-Type: application/json
Accept: application/json

{
    "user_id": "1",
    "follow_id": "50"
}

###フォロー解除
POST http://localhost:8000/api/follows/destroy
Content-Type: application/json
Accept: application/json

{
    "user_id": "1",
    "follow_id": "50"
}

###メール更新
POST http://localhost:8000/api/mails/update
Content-Type: application/json
Accept: application/json

{
    "user_id": "1",
    "mail_id": "4"
}

###ステージ更新
POST http://localhost:8000/api/stages/update
Content-Type: application/json
Accept: application/json

{
    "id": "3"
}

###所持実績更新
POST http://localhost:8000/api/userAchievement/update
Content-Type: application/json
Accept: application/json

{
    "user_id": "5",
    "achievement_id": "3",
    "progress": "14"
}

###デッキ検索結果取得
GET http://localhost:8000/api/battleMode/deck/show
Accept: application/json
Authorization: Bearer 3|Xt6lri1apieCIbDqPq0eaEYVZbIwGG4zxV1eo030fb5475d7

###デッキ更新
POST http://localhost:8000/api/battleMode/deck/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|Xt6lri1apieCIbDqPq0eaEYVZbIwGG4zxV1eo030fb5475d7

{
    "card1": "1",
    "card2": "1"
}

###防衛デッキ更新
POST http://localhost:8000/api/battleMode/defenceDeck/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|BuDlyOyDZjrgniu0in6vqHUnL7xBlew9HOkSPnCA82ebc553

{
    "card_id": "3"
}

###使用済みカード消去
POST http://localhost:8000/api/battleMode/usedCard/destroy
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|BuDlyOyDZjrgniu0in6vqHUnL7xBlew9HOkSPnCA82ebc553

{
    "card_id": "3",
    "stack": "5"
}

###リザルト更新
POST http://localhost:8000/api/battleMode/result/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|BuDlyOyDZjrgniu0in6vqHUnL7xBlew9HOkSPnCA82ebc553

{
    "judge": "1",
    "battle_user_id": "8"
}

###VM FindUser
GET https://api-deadlydraw.japaneast.cloudapp.azure.com/api/users/10
Accept: application/json

###VM ShowStages
GET https://api-deadlydraw.japaneast.cloudapp.azure.com/api/stages
Accept: application/json

###VM ShowItems
GET https://api-deadlydraw.japaneast.cloudapp.azure.com/api/items
Accept: application/json

###VM ShowBattleMode
GET https://api-deadlydraw.japaneast.cloudapp.azure.com/api/battleMode
Accept: application/json

###VM Show UsableCard
GET https://api-deadlydraw.japaneast.cloudapp.azure.com/api/battleMode/usableCard
Accept: application/json

###VM Show Show BattleMode Profile
GET https://api-deadlydraw.japaneast.cloudapp.azure.com/api/battleMode/show/3
Accept: application/json

###Show Deck
GET https://api-deadlydraw.japaneast.cloudapp.azure.com/api/battleMode/deck/show
Accept: application/json
Authorization: Bearer 16|xJ8AdpN5V9fWB4uTfAlu6e6TAvazSqRz4En4ngoo132fbb07

###デッキ更新
POST https://api-deadlydraw.japaneast.cloudapp.azure.com/api/battleMode/deck/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 16|xJ8AdpN5V9fWB4uTfAlu6e6TAvazSqRz4En4ngoo132fbb07

{
    "card1": "1",
    "card2": "1",
    "card3": "2",
    "card4": "3"
}
